Starting Training
Explainibility training started
Begin epoch 0
Batch 0 of 882 of epoch 0
Discriminator Step 1 of 1
/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/autograd/graph.py:769: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Generator step 3 of 3
Batch 1 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 2 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 3 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 4 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 5 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 6 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 7 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 8 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 9 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 10 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 11 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 12 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 13 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 14 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 15 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 16 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 17 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 18 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 19 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 20 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 21 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 22 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 23 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 24 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 25 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 26 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 27 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 28 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 29 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 30 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 31 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 32 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 33 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 34 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 35 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 36 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 37 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 38 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 39 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 40 of 882 of epoch 0
Discriminator Step 1 of 1
Generator step 3 of 3
Batch 41 of 882 of epoch 0
Exception ignored in: <function _releaseLock at 0x79dba45fde40>
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 243, in _releaseLock
    def _releaseLock():

KeyboardInterrupt:
Traceback (most recent call last):
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/training.py", line 158, in trainExplainabilityNetworks
    abnormal_data, flag = next(abnormal_data_iter)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1317, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/kclExplainability.py", line 210, in <module>
    T.trainExplainabilityNetworks(discriminator=discriminator,
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/training.py", line 161, in trainExplainabilityNetworks
    abnormal_data, flag = next(abnormal_data_iter)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1327, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1293, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1131, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 440, in _poll
    r = wait([self], timeout)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 1136, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
