2024-10-18 22:53:11,907 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Current SDK version is 0.18.0
2024-10-18 22:53:11,908 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Configure stats pid to 561854
2024-10-18 22:53:11,909 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Loading settings from /home/collab/deekshith.dade/.config/wandb/settings
2024-10-18 22:53:11,911 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Loading settings from /usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/wandb/settings
2024-10-18 22:53:11,912 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-10-18 22:53:11,913 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-10-18 22:53:11,913 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'dummyData.py', 'program_abspath': '/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/dummyData.py', 'program': '/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/dummyData.py'}
2024-10-18 22:53:11,914 INFO    MainThread:561854 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-10-18 22:53:11,916 INFO    MainThread:561854 [wandb_init.py:_log_setup():525] Logging user logs to /usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/wandb/run-20241018_225311-8g4kkauh/logs/debug.log
2024-10-18 22:53:11,917 INFO    MainThread:561854 [wandb_init.py:_log_setup():526] Logging internal logs to /usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/explainability/wandb/run-20241018_225311-8g4kkauh/logs/debug-internal.log
2024-10-18 22:53:11,918 INFO    MainThread:561854 [wandb_init.py:init():609] calling init triggers
2024-10-18 22:53:11,920 INFO    MainThread:561854 [wandb_init.py:init():616] wandb.init called with sweep_config: {}
config: {'learning_rate': [0.001, 0.0001], 'lossType': 'wgan', 'loassParams': {'learningRate_gen': 0.001, 'learningRate_dis': 0.0001, 'type': 'wgan', 'weights': {'discriminatorWeight': 1.0, 'descrimFakeWeight': 1.0, 'descrimTrueWeight': 1.0, 'classificationWeight': 1.0, 'generatorWeight': 1.0, 'gradWeight': 100.0, 'modificationWeight': 1}}, 'batchSize': 16, 'architecture': 'networkLabel', 'dataset_id': 'SynthSins', 'optimType': 'adam', 'randSeed': 7777, 'genIter_perEp': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 'discrimIter_perEp': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'classificationIter_perEp': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'modPenalties': {'method': ['l1', 'l1_dt'], 'weights': [1e-05, 0.01]}}
2024-10-18 22:53:11,921 INFO    MainThread:561854 [wandb_init.py:init():659] starting backend
2024-10-18 22:53:11,922 INFO    MainThread:561854 [wandb_init.py:init():663] setting up manager
2024-10-18 22:53:11,934 INFO    MainThread:561854 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-18 22:53:11,951 INFO    MainThread:561854 [wandb_init.py:init():671] backend started and connected
2024-10-18 22:53:11,969 INFO    MainThread:561854 [wandb_init.py:init():766] updated telemetry
2024-10-18 22:53:11,971 INFO    MainThread:561854 [wandb_init.py:init():799] communicating run to backend with 90.0 second timeout
2024-10-18 22:53:12,124 ERROR   MainThread:561854 [wandb_init.py:init():825] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-10-18 22:53:12,124 ERROR   MainThread:561854 [wandb_init.py:init():1244] error in wandb.init()
Traceback (most recent call last):
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1234, in init
    return wi.init()
           ^^^^^^^^^
  File "/usr/sci/cibc/ProjectsAndScratch/DeekshithMLECG/dev_env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 831, in init
    raise error
wandb.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-10-18 22:53:12,355 WARNING MsgRouterThr:561854 [router.py:message_loop():77] message_loop has been closed
